#!/bin/bash

stem=01050ApplyDMM2_epara_allseed_t1w1
datadir=00153MakeData.out
train_iter=50
test_iter=50
com=`pwd`/dmm2
opt="-t1 -w1 +save_ll +llgivenk -seed 1"
alpha="1.0"
beta="1.0"
streams="NodeFRT NodeLFT NodeRIT"

n=8;   ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=9;   ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=10;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=11;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=12;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=13;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=14;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=15;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=16;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=17;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=18;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=19;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=20;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=21;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=22;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=23;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=24;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=25;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=26;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=27;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=28;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=29;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=30;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=31;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=32;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=33;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=34;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=35;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=36;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=37;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=38;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=39;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=40;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=50;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=60;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=70;  ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=100; ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
n=200; ./ApplyDMM2.epara_allseed.sh $n $alpha $beta $train_iter $test_iter $stem $datadir $com "$streams" "$opt" &
